services: mongodb
language: node_js
node_js:
  - "5.11"
addons:
    code_climate:
        repo_token: f97b0540d8ec7393081d1ba47fc68803bab166052d478bd04a46164e2ee32ba7
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info